<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Res\IcoE.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>WeChatAntiRecall</AssemblyName>
    <RootNamespace>WeChatAntiRecall</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Res\IcoE.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="capstone" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\config.yml" Link="config.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config3.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
